name: qqnews

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: Checkout qqnews_image repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ${{ github.actor }}/QQ_News_Images
          token: ${{ secrets.QQNEWS_IMAGE_TOKEN }}
          path: ./qqnews_image

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.github_email }}
          git config --global user.name ${{ github.actor }}
          git remote set-url origin https://${{ secrets.QQNEWS_IMAGE_TOKEN }}@github.com/${{ github.actor }}/qqnews.git

          git pull --rebase

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python qq.py

      - name: Generate index page
        run: python index_generator.py

      - name: Commit changes
        run: |
          git add .
          git commit --allow-empty -m "spider"
          git push

      - name: Push images to qqnews_image repository
        run: |
          cd qqnews_image
          git remote set-url origin https://${{ secrets.QQNEWS_IMAGE_TOKEN }}@github.com/${{ github.actor }}/QQ_News_Images.git
          git add .
          git commit --allow-empty -m "Add images"
          git push
