name: qqnews

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout qqnews_image repository
        uses: actions/checkout@v2
        with:
          repository: qqhsx/qqnews_image
          token: ${{ secrets.QQNEWS_IMAGE_TOKEN }}
          path: ./qqnews_image

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'

      - name: Install dependencies and run script
        run: |
          git config --local user.email "378600950@qq.com"
          git config --local user.name "qqhsx"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.QQNEWS_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          pip3 install requests
          pip3 install bs4
          pip3 install html2text
          python qq.py
          # python index_generator.py
          git add .
          ls -l
          git commit --allow-empty -m "spider"
          git push -f

      - name: Push images to qqnews_image repository
        run: |
          cd qqnews_image
          git config --local user.email "378600950@qq.com"
          git config --local user.name "qqhsx"
          git add .
          git commit --allow-empty -m "Add images"
          git push
